sonata_admin:
    title: 'Administration'
    dashboard:
        blocks:
             -
                position: top
                class: col-md-12
                type: sonata.block.service.text
                settings: 
                    content: >
                        <h1 class="dashboard-title">Tableau de bord</h1>
                        <p class="description">Bienvenue sur le panneau d'administration. 
                        Ici, vous allez pouvoir administrer l'encyclopédie et ses membres.</p>
             - { type: sonata.admin.block.admin_list, position: left }
    assets:
        extra_stylesheets: [ assets/admin.css ]
            

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
