version: '3'

services:
  app:
    container_name: wiki_php
    build: ./docker/prod
    ports:
      - "9000:9000"
    volumes:
      - ./application:/var/www
    networks:
      - network-wiki

  nginx:
    container_name: wiki_nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./application:/var/www
      - ./docker/prod/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - network-wiki

  database:
    image: mysql:latest
    container_name: wiki_database
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: main
    ports:
      - '3306'
    networks:
      - network-wiki

volumes:
  db-data:


networks:
  network-wiki:
