version: '3'

services:
  database:
    image: 'mysql:latest'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: main
    ports:
      - '3306'

volumes:
  ###> doctrine/doctrine-bundle ###
  db-data: ###< doctrine/doctrine-bundle ###
