twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']

    globals:
        app_name: '%env(WIKI_NAME)%'
        app_description: '%env(WIKI_DESCRIPTION)%'

when@test:
    twig:
        strict_variables: true
